#!/bin/bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATABASE_NAME="krispoint"
APPLICATION_USER="krispoint_app"
ENV_PATH="$PROJECT_ROOT/.env"
VOICE_DIR="$PROJECT_ROOT/vosk-server"
VOICE_ENV_PATH="$VOICE_DIR/.env"
VOICE_PYTHON="$VOICE_DIR/.venv/bin/python"

fail() {
  printf '\nERROR: %s\n' "$1" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 was not found. $2"
}

read_default() {
  local prompt="$1"
  local default_value="$2"
  local value
  read -r -p "$prompt [$default_value]: " value
  printf '%s' "${value:-$default_value}"
}

cd "$PROJECT_ROOT"

printf '%s\n' "========================================"
printf '%s\n' " KrisPoint First-Time Setup - macOS"
printf '%s\n\n' "========================================"

BREW=""
if [ -x /opt/homebrew/bin/brew ]; then
  BREW=/opt/homebrew/bin/brew
elif [ -x /usr/local/bin/brew ]; then
  BREW=/usr/local/bin/brew
elif command -v brew >/dev/null 2>&1; then
  BREW="$(command -v brew)"
fi

if [ -n "$BREW" ]; then
  eval "$("$BREW" shellenv)"
  BREW_PREFIX="$("$BREW" --prefix)"
  export PATH="$BREW_PREFIX/opt/node@20/bin:$BREW_PREFIX/opt/postgresql@15/bin:$BREW_PREFIX/opt/python@3.11/bin:$PATH"
fi

require_command node "Install Node.js 20 or later, for example with: brew install node@20"
require_command npm "Install Node.js 20 or later, for example with: brew install node@20"
require_command psql "Install PostgreSQL 15 or later, for example with: brew install postgresql@15"
require_command createdb "Install PostgreSQL command-line tools and add them to PATH."

NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"
if [ "$NODE_MAJOR" -lt 20 ]; then
  fail "Node.js 20 or later is required. Installed version: $(node --version)"
fi

if [ -f "$ENV_PATH" ]; then
  printf '%s\n' "An existing .env file was found."
  printf '%s\n' "Its database credentials and encryption key will be preserved."
  printf '%s\n' "To protect existing encrypted patient data, this installer never replaces them."
  npm ci --ignore-scripts --no-audit --no-fund
  npm run db:push
  printf '\nExisting KrisPoint installation verified successfully.\n'
  printf 'Run setup-voice-server.bat or configure voice manually if needed.\n'
  exit 0
fi

DATABASE_HOST="$(read_default "PostgreSQL host" "localhost")"
DATABASE_PORT="$(read_default "PostgreSQL port" "5432")"
ADMINISTRATOR="$(read_default "PostgreSQL administrator username" "$USER")"
read -r -s -p "PostgreSQL administrator password (not saved): " ADMINISTRATOR_PASSWORD
printf '\n'

APPLICATION_PASSWORD="$(node -e "process.stdout.write(require('crypto').randomBytes(24).toString('hex'))")"
ENCRYPTION_KEY="$(node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))")"

export PGPASSWORD="$ADMINISTRATOR_PASSWORD"
trap 'unset PGPASSWORD ADMINISTRATOR_PASSWORD HF_TOKEN' EXIT

if ! psql --host "$DATABASE_HOST" --port "$DATABASE_PORT" --username "$ADMINISTRATOR" --dbname postgres --command "SELECT 1" >/dev/null; then
  fail "Could not connect to PostgreSQL. Check the host, port, username, password, and that PostgreSQL is running."
fi

ROLE_EXISTS="$(psql --host "$DATABASE_HOST" --port "$DATABASE_PORT" --username "$ADMINISTRATOR" --dbname postgres --tuples-only --no-align --command "SELECT 1 FROM pg_roles WHERE rolname = '$APPLICATION_USER';")"
if [ "$ROLE_EXISTS" = "1" ]; then
  psql --host "$DATABASE_HOST" --port "$DATABASE_PORT" --username "$ADMINISTRATOR" --dbname postgres --set ON_ERROR_STOP=1 --command "ALTER ROLE $APPLICATION_USER WITH LOGIN PASSWORD '$APPLICATION_PASSWORD';"
else
  psql --host "$DATABASE_HOST" --port "$DATABASE_PORT" --username "$ADMINISTRATOR" --dbname postgres --set ON_ERROR_STOP=1 --command "CREATE ROLE $APPLICATION_USER LOGIN PASSWORD '$APPLICATION_PASSWORD';"
fi

DATABASE_EXISTS="$(psql --host "$DATABASE_HOST" --port "$DATABASE_PORT" --username "$ADMINISTRATOR" --dbname postgres --tuples-only --no-align --command "SELECT 1 FROM pg_database WHERE datname = '$DATABASE_NAME';")"
if [ "$DATABASE_EXISTS" = "1" ]; then
  psql --host "$DATABASE_HOST" --port "$DATABASE_PORT" --username "$ADMINISTRATOR" --dbname postgres --set ON_ERROR_STOP=1 --command "ALTER DATABASE $DATABASE_NAME OWNER TO $APPLICATION_USER;"
else
  createdb --host "$DATABASE_HOST" --port "$DATABASE_PORT" --username "$ADMINISTRATOR" --owner "$APPLICATION_USER" "$DATABASE_NAME"
fi

unset PGPASSWORD ADMINISTRATOR_PASSWORD

DATABASE_URL="postgresql://${APPLICATION_USER}:${APPLICATION_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"
cat > "$ENV_PATH" <<EOF
# Generated by KrisPoint first-time setup.
DATABASE_URL=$DATABASE_URL
ENCRYPTION_KEY=$ENCRYPTION_KEY
VITE_VOSK_SERVER_URL=
NODE_ENV=development
EOF
chmod 600 "$ENV_PATH"

export DATABASE_URL ENCRYPTION_KEY
npm ci --ignore-scripts --no-audit --no-fund
npm run db:push

read -r -p "Install local MedASR voice recognition on this computer? [y/N]: " install_voice
if [[ "$install_voice" =~ ^[Yy]$ ]]; then
  require_command python3.11 "Install Python 3.11, for example with: brew install python@3.11"

  python3.11 -c "import struct, sys; assert sys.version_info[:2] == (3, 11); assert struct.calcsize('P') * 8 == 64" ||
    fail "Voice recognition requires 64-bit Python 3.11."

  if [ ! -x "$VOICE_PYTHON" ]; then
    python3.11 -m venv "$VOICE_DIR/.venv"
  fi
  "$VOICE_PYTHON" -m pip install --upgrade pip
  "$VOICE_PYTHON" -m pip install -r "$VOICE_DIR/requirements.txt"
  "$VOICE_PYTHON" -c "import faster_whisper; import torch; import transformers; import websockets"

  printf '\nAccept the MedASR terms at https://huggingface.co/google/medasr\n'
  read -r -s -p "Read-only Hugging Face token: " HF_TOKEN
  printf '\n'
  [ -n "$HF_TOKEN" ] || fail "A Hugging Face token is required for the first MedASR download."

  cat > "$VOICE_ENV_PATH" <<EOF
ASR_ENGINE=medasr
MEDASR_MODEL_ID=google/medasr
MEDASR_DEVICE=cpu
MEDASR_CPU_THREADS=4
MEDASR_MIN_SILENCE_SECONDS=0.5
MEDASR_MAX_UTTERANCE_SECONDS=20
HF_TOKEN=$HF_TOKEN
VOICE_HOST=127.0.0.1
VOICE_PORT=8000
SAMPLE_RATE=16000
CHUNK_SIZE=8000
EOF
  chmod 600 "$VOICE_ENV_PATH"
  unset HF_TOKEN
fi

printf '\nKrisPoint setup completed successfully.\n'
printf 'Start the application with: npm run dev\n'
if [[ "$install_voice" =~ ^[Yy]$ ]]; then
  printf 'Start voice recognition with: ./start-voice-server-macos.command\n'
fi