$ErrorActionPreference = "Stop"
$msi = Get-ChildItem "src-tauri/target/release/bundle/msi/*.msi" | Select-Object -First 1
if (-not $msi) { throw "MSI installer was not produced" }

$installLog = Join-Path $env:RUNNER_TEMP "krispoint-install.log"
$uninstallLog = Join-Path $env:RUNNER_TEMP "krispoint-uninstall.log"

function Invoke-Msi([string]$Arguments) {
  $process = Start-Process msiexec.exe -ArgumentList $Arguments -Wait -PassThru
  if ($process.ExitCode -ne 0) { throw "msiexec failed with exit code $($process.ExitCode)" }
}

# Clean install, rerun/repair, and upgrade semantics all use the same stable
# product identifier generated by Tauri/WiX.
Invoke-Msi "/i `"$($msi.FullName)`" /qn /norestart /L*v `"$installLog`""
Invoke-Msi "/i `"$($msi.FullName)`" REINSTALL=ALL REINSTALLMODE=vomus /qn /norestart"

$installed = Get-ChildItem @($env:LOCALAPPDATA, $env:ProgramFiles) -Filter "KrisPoint.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $installed) { throw "KrisPoint.exe was not installed" }
$originalPath = $env:PATH
$env:PATH = "$env:SystemRoot\System32;$env:SystemRoot"
$app = Start-Process $installed.FullName -PassThru
Start-Sleep -Seconds 10
if ($app.HasExited) { throw "KrisPoint exited during launch smoke test" }
Stop-Process -Id $app.Id -Force
$env:PATH = $originalPath

$voice = Get-ChildItem $installed.Directory.FullName -Filter "krispoint-voice.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $voice) { throw "Installed MedASR executable is missing" }
$firewallRule = "KrisPoint offline installer smoke $PID"
try {
  $activeCategories = Get-NetConnectionProfile | Select-Object -ExpandProperty NetworkCategory -Unique
  if (-not $activeCategories) { throw "No active Windows network profile was found" }
  foreach ($category in $activeCategories) {
    $profileName = if ($category -eq "DomainAuthenticated") { "Domain" } else { $category }
    $profile = Get-NetFirewallProfile -Name $profileName
    if (-not $profile.Enabled) {
      throw "Windows Firewall profile $profileName must be enabled for the offline transcription smoke test"
    }
  }
  New-NetFirewallRule -DisplayName $firewallRule -Direction Outbound -Action Block -Profile Any -Program $voice.FullName | Out-Null
  $rule = Get-NetFirewallRule -DisplayName $firewallRule -ErrorAction Stop
  if (-not $rule.Enabled -or $rule.Profile -ne "Any") {
    throw "Offline firewall rule was not enabled"
  }
  python scripts/verify-installed-voice.py --application $installed.FullName --audio training_data/audio/1/session_1766430738966_1urld97w9.wav
  if ($LASTEXITCODE -ne 0) { throw "Offline MedASR transcription smoke test failed" }
} finally {
  Remove-NetFirewallRule -DisplayName $firewallRule -ErrorAction SilentlyContinue
}

Invoke-Msi "/x `"$($msi.FullName)`" /qn /norestart /L*v `"$uninstallLog`""
if (Test-Path $installed.FullName) { throw "KrisPoint executable remained after uninstall" }