$ErrorActionPreference = "Stop"
$msi = Get-ChildItem "src-tauri/target/release/bundle/msi/*.msi" | Select-Object -First 1
if (-not $msi) { throw "MSI installer was not produced" }

$installLog = Join-Path $env:RUNNER_TEMP "krispoint-install.log"
$uninstallLog = Join-Path $env:RUNNER_TEMP "krispoint-uninstall.log"

function Invoke-Msi([string]$Arguments) {
  $process = Start-Process msiexec.exe -ArgumentList $Arguments -Wait -PassThru
  if ($process.ExitCode -ne 0) { throw "msiexec failed with exit code $($process.ExitCode)" }
}

# Clean install and rerun/repair semantics use the same stable product
# identifier generated by Tauri/WiX.
Invoke-Msi "/i `"$($msi.FullName)`" /qn /norestart /L*v `"$installLog`""
Invoke-Msi "/i `"$($msi.FullName)`" REINSTALL=ALL REINSTALLMODE=vomus /qn /norestart"

$installed = Get-ChildItem @($env:LOCALAPPDATA, $env:ProgramFiles) -Filter "KrisPoint.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $installed) { throw "KrisPoint.exe was not installed" }

$voice = Get-ChildItem $installed.Directory.FullName -Filter "krispoint-voice.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $voice) { throw "Installed MedASR executable is missing" }
$firewallRule = "KrisPoint offline installer smoke $PID"
try {
  $disabledProfiles = Get-NetFirewallProfile | Where-Object { -not $_.Enabled }
  if ($disabledProfiles) {
    $profileNames = ($disabledProfiles | Select-Object -ExpandProperty Name) -join ", "
    throw "Windows Firewall profiles must be enabled for the offline transcription smoke test; disabled: $profileNames"
  }
  New-NetFirewallRule -DisplayName $firewallRule -Direction Outbound -Action Block -Profile Any -Program $voice.FullName | Out-Null
  $rule = Get-NetFirewallRule -DisplayName $firewallRule -ErrorAction Stop
  if (-not $rule.Enabled -or $rule.Profile -ne "Any") {
    throw "Offline firewall rule was not enabled"
  }
  python scripts/verify-installed-voice.py --application $installed.FullName --audio training_data/audio/1/session_1766430738966_1urld97w9.wav
  if ($LASTEXITCODE -ne 0) { throw "Offline MedASR transcription smoke test failed" }
} finally {
  Remove-NetFirewallRule -DisplayName $firewallRule -ErrorAction SilentlyContinue
}

Invoke-Msi "/x `"$($msi.FullName)`" /qn /norestart /L*v `"$uninstallLog`""
if (Test-Path $installed.FullName) { throw "KrisPoint executable remained after uninstall" }